BEGIN TRANSACTION;
CREATE TABLE groups(id INTEGER PRIMARY KEY AUTOINCREMENT,name varchar(64),info varchar(128),pos int);
INSERT INTO "groups" VALUES(1,'WinControls','Интерфейс',1);
INSERT INTO "groups" VALUES(2,'Controls','Контролы',2);
INSERT INTO "groups" VALUES(3,'Graphics','Графика',3);
INSERT INTO "groups" VALUES(4,'Windows','Окно',4);
INSERT INTO "groups" VALUES(5,'System','Система',5);
INSERT INTO "groups" VALUES(6,'Internet','Интернет',9);
INSERT INTO "groups" VALUES(7,'DataBase','Базы данных',10);
INSERT INTO "groups" VALUES(8,'Files','Файлы',11);
INSERT INTO "groups" VALUES(9,'Logic','Логика',12);
INSERT INTO "groups" VALUES(10,'Arrays','Массивы',13);
INSERT INTO "groups" VALUES(11,'Tools','Инструменты',14);
INSERT INTO "groups" VALUES(12,'LowLevel','Примитивы',18);
INSERT INTO "groups" VALUES(13,'Strings','Строки',8);
INSERT INTO "groups" VALUES(14,'Consts','Константы',17);
INSERT INTO "groups" VALUES(15,'Helpers','Помощники',16);
INSERT INTO "groups" VALUES(16,'',NULL,19);
INSERT INTO "groups" VALUES(17,'CodeGen','Кодогенератор',20);
INSERT INTO "groups" VALUES(18,'Media','Мультимедиа',7);
INSERT INTO "groups" VALUES(19,'WMI','Администрирование',6);
INSERT INTO "groups" VALUES(20,'MultiThread','МТ потоки',15);
DELETE FROM sqlite_sequence;
INSERT INTO "sqlite_sequence" VALUES('groups',20);
INSERT INTO "sqlite_sequence" VALUES('elements',292);
CREATE TABLE elements(id INTEGER PRIMARY KEY AUTOINCREMENT,name varchar(64),info varchar(64),tab int,pos int,hash varchar(32));
INSERT INTO "elements" VALUES(1,'Label','Надпись',1,1,NULL);
INSERT INTO "elements" VALUES(2,'CheckBox','Флажок',1,2,NULL);
INSERT INTO "elements" VALUES(3,'RadioButton','Переключатель',1,3,NULL);
INSERT INTO "elements" VALUES(4,'Button','Кнопка',1,4,NULL);
INSERT INTO "elements" VALUES(5,'Edit','Ввод текста',1,5,NULL);
INSERT INTO "elements" VALUES(6,'ComboBox','Выпадающий список',1,6,NULL);
INSERT INTO "elements" VALUES(7,'RichEdit','Расширенный редактор',1,7,NULL);
INSERT INTO "elements" VALUES(8,'StringTable','Таблица строк',1,8,NULL);
INSERT INTO "elements" VALUES(9,'Calendar','Календарь',1,9,NULL);
INSERT INTO "elements" VALUES(10,'DatePicker','Выпадающий календарь',1,10,NULL);
INSERT INTO "elements" VALUES(11,'Image','Изображение',1,11,NULL);
INSERT INTO "elements" VALUES(12,'WebBrowser','Обозреватель интернета',1,12,NULL);
INSERT INTO "elements" VALUES(13,'Menu','Панель меню',1,13,NULL);
INSERT INTO "elements" VALUES(14,'StatusBar','Панель статуса',1,14,NULL);
INSERT INTO "elements" VALUES(15,'PopupMenu','Контекстное меню',1,15,NULL);
INSERT INTO "elements" VALUES(16,'ListBox','Спиcoк строк',1,16,NULL);
INSERT INTO "elements" VALUES(17,'ProgressBar','Статус процесса',1,17,NULL);
INSERT INTO "elements" VALUES(18,'ScrollBar','Полоса прокрутки',1,18,NULL);
INSERT INTO "elements" VALUES(19,'TrackBar','Ползунок выбора',1,19,NULL);
INSERT INTO "elements" VALUES(20,'UpDown','Шаговый модификатор',1,20,NULL);
INSERT INTO "elements" VALUES(21,'IPAddress','Редактор IP адреса',1,21,NULL);
INSERT INTO "elements" VALUES(22,'HyperLink','Гиперссылка',1,22,NULL);
INSERT INTO "elements" VALUES(23,'Animate','Проигрыватель',1,23,NULL);
INSERT INTO "elements" VALUES(24,'HotKey','Горячая клавиша',1,24,NULL);
INSERT INTO "elements" VALUES(25,'ListView','Представление списка',1,25,NULL);
INSERT INTO "elements" VALUES(26,'TreeView','Дерево элементов',1,26,NULL);
INSERT INTO "elements" VALUES(27,'Splitter','Изменение размеров элементов',1,27,NULL);
INSERT INTO "elements" VALUES(28,'HeaderView','Заголовки колонок',1,28,NULL);
INSERT INTO "elements" VALUES(29,'ToolBar','Панель кнопок',1,29,NULL);
INSERT INTO "elements" VALUES(30,'*Interface_Диалоги','Диалоги',1,30,NULL);
INSERT INTO "elements" VALUES(31,'FontDialog','Выбор шрифта',1,31,NULL);
INSERT INTO "elements" VALUES(32,'ColorDialog','Выбор цвета',1,32,NULL);
INSERT INTO "elements" VALUES(33,'FindDialog','Поиск и замена текста',1,33,NULL);
INSERT INTO "elements" VALUES(34,'PageSetupDialog','Настройка страницы',1,34,NULL);
INSERT INTO "elements" VALUES(35,'PrintDialog','Диалог печати',1,35,NULL);
INSERT INTO "elements" VALUES(36,'*Interface_Контейнеры','Контейнеры',1,36,NULL);
INSERT INTO "elements" VALUES(37,'ContainerChildForm','Дочерняя форма',1,37,NULL);
INSERT INTO "elements" VALUES(38,'ContainerDialogForm','Дочерняя диалоговая форма',1,38,NULL);
INSERT INTO "elements" VALUES(39,'ChildPanel','Панель',1,39,NULL);
INSERT INTO "elements" VALUES(40,'ChildPanelEx','Панель',1,40,NULL);
INSERT INTO "elements" VALUES(41,'ChildGroupBox','Группа элементов',1,41,NULL);
INSERT INTO "elements" VALUES(42,'ChildGroupBoxEx','Группа элементов',1,42,NULL);
INSERT INTO "elements" VALUES(43,'ChildReBar','Контейнер',1,43,NULL);
INSERT INTO "elements" VALUES(44,'ChildPager','Контейнер',1,44,NULL);
INSERT INTO "elements" VALUES(45,'ChildTab','Контейнер',1,45,NULL);
INSERT INTO "elements" VALUES(46,'ChildTabControl','Контейнер',1,46,NULL);
INSERT INTO "elements" VALUES(47,'Timer','Таймер',2,1,NULL);
INSERT INTO "elements" VALUES(48,'Echo','Вывод текста',2,2,NULL);
INSERT INTO "elements" VALUES(49,'MessageBox','Окно сообщения',2,3,NULL);
INSERT INTO "elements" VALUES(50,'Prompt','Ввод текста',2,4,NULL);
INSERT INTO "elements" VALUES(51,'EventBehavior','Менеджер событий',2,5,NULL);
INSERT INTO "elements" VALUES(52,'StringsControl','Менеджер строк',2,6,NULL);
INSERT INTO "elements" VALUES(53,'StatusItem','Настройка статуса',2,7,NULL);
INSERT INTO "elements" VALUES(54,'FontEx','Настройки шрифта',2,8,NULL);
INSERT INTO "elements" VALUES(55,'Brush','Настройки кисти',2,9,NULL);
INSERT INTO "elements" VALUES(56,'Pen','Настройки пера',2,10,NULL);
INSERT INTO "elements" VALUES(57,'EditControl','Настройка редактора',2,11,NULL);
INSERT INTO "elements" VALUES(58,'ReBarBand','Настройка ReBar',2,12,NULL);
INSERT INTO "elements" VALUES(59,'HintControl','Менеджер подсказки',2,13,NULL);
INSERT INTO "elements" VALUES(60,'ListViewColumns','Заголовки списка',2,14,NULL);
INSERT INTO "elements" VALUES(61,'ListItem','Элемент списка',2,15,NULL);
INSERT INTO "elements" VALUES(62,'HeaderItem','Настройка заголовка',2,16,NULL);
INSERT INTO "elements" VALUES(63,'PrintInfo','Настройки печати',2,17,NULL);
INSERT INTO "elements" VALUES(64,'ActiveXControl','Элемент управления',2,18,NULL);
INSERT INTO "elements" VALUES(65,'TreeItem','Элемент дерева',2,19,NULL);
INSERT INTO "elements" VALUES(66,'HeaderControl','Настройка заголовков',2,20,NULL);
INSERT INTO "elements" VALUES(67,'Action','Действие',2,21,NULL);
INSERT INTO "elements" VALUES(68,'Rectangle','Прямоугольник',3,1,NULL);
INSERT INTO "elements" VALUES(69,'Line','Прямая',3,2,NULL);
INSERT INTO "elements" VALUES(70,'Ellipse','Эллипс',3,3,NULL);
INSERT INTO "elements" VALUES(71,'Arc','Дуга',3,4,NULL);
INSERT INTO "elements" VALUES(72,'Bevel','Рамка',3,5,NULL);
INSERT INTO "elements" VALUES(73,'Chord','Хорда',3,6,NULL);
INSERT INTO "elements" VALUES(74,'Circle','Окружность',3,7,NULL);
INSERT INTO "elements" VALUES(75,'Pie','Доля',3,8,NULL);
INSERT INTO "elements" VALUES(76,'RoundRect','Прямоугольник скруглённый',3,9,NULL);
INSERT INTO "elements" VALUES(77,'Polygon','Полигон',3,10,NULL);
INSERT INTO "elements" VALUES(78,'TextOut','Текст',3,11,NULL);
INSERT INTO "elements" VALUES(79,'LoadImage','Загрузка картинки',3,12,NULL);
INSERT INTO "elements" VALUES(80,'ImageList','Список изображений',3,13,NULL);
INSERT INTO "elements" VALUES(81,'WinEnum','Перебор окон',4,1,NULL);
INSERT INTO "elements" VALUES(82,'WinTools','Операции над окнами',4,2,NULL);
INSERT INTO "elements" VALUES(83,'FindWindow','Поиск окона',4,3,NULL);
INSERT INTO "elements" VALUES(84,'SizeWindow','Размер окна',4,4,NULL);
INSERT INTO "elements" VALUES(85,'PosWindow','Положение окна',4,5,NULL);
INSERT INTO "elements" VALUES(86,'MoveControl','Перемещение контрола',4,6,NULL);
INSERT INTO "elements" VALUES(87,'SendMessage','Посылка сообщений',4,7,NULL);
INSERT INTO "elements" VALUES(88,'*Windows_Regions','Регионы',4,8,NULL);
INSERT INTO "elements" VALUES(89,'RectRgn','Прямоугольный регион',4,9,NULL);
INSERT INTO "elements" VALUES(90,'EllipticRgn','Эллиптический регион',4,10,NULL);
INSERT INTO "elements" VALUES(91,'RoundRectRgn','Прямоугольный регион',4,11,NULL);
INSERT INTO "elements" VALUES(92,'PolygonRgn','Сложный регион',4,12,NULL);
INSERT INTO "elements" VALUES(93,'CombineRgn','Объединение регионов',4,14,NULL);
INSERT INTO "elements" VALUES(94,'RgnFromImage','Регион из картинки',4,13,NULL);
INSERT INTO "elements" VALUES(95,'EqualRgn','Сравнение регионов',4,15,NULL);
INSERT INTO "elements" VALUES(96,'TransformRgn','Изменение региона',4,16,NULL);
INSERT INTO "elements" VALUES(97,'Application','Параметры сценария',5,1,NULL);
INSERT INTO "elements" VALUES(98,'WinExec','Запуск приложений',5,2,NULL);
INSERT INTO "elements" VALUES(99,'LogEvent','Журнал событий',5,3,NULL);
INSERT INTO "elements" VALUES(100,'GUID','Глобальный идентификатор',5,4,NULL);
INSERT INTO "elements" VALUES(101,'Zipper','Zip архиватор',5,5,NULL);
INSERT INTO "elements" VALUES(102,'Font','Установка шрифта',5,6,NULL);
INSERT INTO "elements" VALUES(103,'Clipboard','Буфер Обмена Windows',5,7,NULL);
INSERT INTO "elements" VALUES(104,'Registry','Чтение/Запись в реестр',5,8,NULL);
INSERT INTO "elements" VALUES(105,'DrivesInfo','Информация о дисках',5,9,NULL);
INSERT INTO "elements" VALUES(106,'ExitWindowsDialog','Диалог выхода из системы',5,10,NULL);
INSERT INTO "elements" VALUES(107,'Time','Текущее время',5,11,NULL);
INSERT INTO "elements" VALUES(108,'Ping','Компьютер в сети?',6,1,NULL);
INSERT INTO "elements" VALUES(109,'NsLookup','Поиск компьютера',6,2,NULL);
INSERT INTO "elements" VALUES(110,'SendEmail','Отправить письмо',6,3,NULL);
INSERT INTO "elements" VALUES(111,'Socket','TCP соединение',6,4,NULL);
INSERT INTO "elements" VALUES(112,'SocketSend','Отсыл данных',6,5,NULL);
INSERT INTO "elements" VALUES(113,'SocketGet','Приём данных',6,6,NULL);
INSERT INTO "elements" VALUES(114,'HttpGet','Загрузка Web страниц',6,7,NULL);
INSERT INTO "elements" VALUES(115,'WinHttp','Запросы к web-серверу',6,8,NULL);
INSERT INTO "elements" VALUES(116,'odbc','ODBC connect',7,1,NULL);
INSERT INTO "elements" VALUES(117,'odbc_exec','Запрос к базе данных',7,2,NULL);
INSERT INTO "elements" VALUES(118,'odbc_enumRS','Перебор данных',7,3,NULL);
INSERT INTO "elements" VALUES(119,'odbc_FieldReader','Чтение данных',7,4,NULL);
INSERT INTO "elements" VALUES(120,'*DataBase_Потоки','Потоки',7,5,NULL);
INSERT INTO "elements" VALUES(121,'ADODBStream','ADODB пoтoк данных',7,6,NULL);
INSERT INTO "elements" VALUES(122,'ADODBStreamRW','Работа с потоком ADODB',7,7,NULL);
INSERT INTO "elements" VALUES(123,'ADODBStreamIO','Обмен данных потока и файла',7,8,NULL);
INSERT INTO "elements" VALUES(124,'ADODBStreamCopy','Копирование потока',7,9,NULL);
INSERT INTO "elements" VALUES(125,'FileTools','Файловые операции',8,1,NULL);
INSERT INTO "elements" VALUES(126,'FilePart','Разделение имени',8,2,NULL);
INSERT INTO "elements" VALUES(127,'FileSearch','Поиск файлов',8,3,NULL);
INSERT INTO "elements" VALUES(128,'SpecFolder','Специальные папки',8,4,NULL);
INSERT INTO "elements" VALUES(129,'DirTools','Операции с папками',8,5,NULL);
INSERT INTO "elements" VALUES(130,'Ini','Работа с INI файлами',8,6,NULL);
INSERT INTO "elements" VALUES(131,'ShortCut','Ярлык файла',8,7,NULL);
INSERT INTO "elements" VALUES(132,'FileQuery','Пoиcк по файловой системе',8,8,NULL);
INSERT INTO "elements" VALUES(133,'*Files_Диалоги','Диалоги',8,9,NULL);
INSERT INTO "elements" VALUES(134,'Browse','Обзор',8,10,NULL);
INSERT INTO "elements" VALUES(135,'ODialog','Открытие файла',8,11,NULL);
INSERT INTO "elements" VALUES(136,'SDialog','Сохранение файла',8,12,NULL);
INSERT INTO "elements" VALUES(137,'FileChooser','Выбор файлов',8,13,NULL);
INSERT INTO "elements" VALUES(138,'*Files_Потоки','Потоки',8,14,NULL);
INSERT INTO "elements" VALUES(139,'FileTextStream','Текстовый пoтoк',8,15,NULL);
INSERT INTO "elements" VALUES(140,'FileTextStreamRW','Чтение и запись потока',8,16,NULL);
INSERT INTO "elements" VALUES(141,'For','Цикл итераций',9,1,NULL);
INSERT INTO "elements" VALUES(142,'If_else','Событие по условию',9,2,NULL);
INSERT INTO "elements" VALUES(143,'Math','Математика',9,3,NULL);
INSERT INTO "elements" VALUES(144,'MathParse','Мат. выражение',9,4,NULL);
INSERT INTO "elements" VALUES(145,'Case','Разветвитель по условию',9,5,NULL);
INSERT INTO "elements" VALUES(146,'Random','Случайное число',9,6,NULL);
INSERT INTO "elements" VALUES(147,'Rand','Случайное число',9,7,NULL);
INSERT INTO "elements" VALUES(148,'Rnd','Случайное число',9,8,NULL);
INSERT INTO "elements" VALUES(149,'While','Цикл с условием',9,9,NULL);
INSERT INTO "elements" VALUES(150,'CaseEx','Разветвитель по условию',9,10,NULL);
INSERT INTO "elements" VALUES(151,'ForEach','Цикл итераций',9,11,NULL);
INSERT INTO "elements" VALUES(152,'Counter','Линейный счетчик',9,12,NULL);
INSERT INTO "elements" VALUES(153,'Repeat','Условный цикл',9,13,NULL);
INSERT INTO "elements" VALUES(154,'ArrayItem','Доступ к массиву',10,1,NULL);
INSERT INTO "elements" VALUES(155,'ArrayEnum','Перебор массива',10,2,NULL);
INSERT INTO "elements" VALUES(156,'ArrayRead','Чтение массива',10,3,NULL);
INSERT INTO "elements" VALUES(157,'ArraySize','Размер массива',10,4,NULL);
INSERT INTO "elements" VALUES(158,'ArrayWrite','Запись в массив',10,5,NULL);
INSERT INTO "elements" VALUES(159,'StrArray','Массив строк',10,6,NULL);
INSERT INTO "elements" VALUES(160,'ArrayRW','Запись и чтение массива',10,7,NULL);
INSERT INTO "elements" VALUES(161,'IntArray','Массив целых чисел',10,8,NULL);
INSERT INTO "elements" VALUES(162,'PointsArray','Массив пар координат',10,9,NULL);
INSERT INTO "elements" VALUES(163,'Matrix','Матрица данных',10,10,NULL);
INSERT INTO "elements" VALUES(164,'MatrixRW','Запись и чтение матрицы',10,11,NULL);
INSERT INTO "elements" VALUES(165,'Dictionary','Словарь',10,12,NULL);
INSERT INTO "elements" VALUES(166,'Hub','Хаб',11,1,NULL);
INSERT INTO "elements" VALUES(167,'GetData','Доступ элементов к данным',11,2,NULL);
INSERT INTO "elements" VALUES(168,'GetIndexData','Доступ по индексу',11,3,NULL);
INSERT INTO "elements" VALUES(169,'DoData','Поток-данные',11,4,NULL);
INSERT INTO "elements" VALUES(170,'EventFromData','Событие обращения к данным',11,5,NULL);
INSERT INTO "elements" VALUES(171,'Memory','Память',11,6,NULL);
INSERT INTO "elements" VALUES(172,'ChanelToIndex','Канал в индекс',11,7,NULL);
INSERT INTO "elements" VALUES(173,'IndexToChanel','Индекс в канал',11,8,NULL);
INSERT INTO "elements" VALUES(174,'Switch','Переключатель',11,9,NULL);
INSERT INTO "elements" VALUES(175,'Stack','Организация стека',11,10,NULL);
INSERT INTO "elements" VALUES(176,'GlobalVar','Глобальная переменная',11,11,NULL);
INSERT INTO "elements" VALUES(177,'Var','Переменная',11,12,NULL);
INSERT INTO "elements" VALUES(178,'MultiElement','Вложенная схема',11,13,NULL);
INSERT INTO "elements" VALUES(179,'MultiElementEx','Вложенная схема',11,14,NULL);
INSERT INTO "elements" VALUES(180,'TimeCounter','Счетчик времени',11,15,NULL);
INSERT INTO "elements" VALUES(181,'KeyMask','Комбинация клавиш',11,16,NULL);
INSERT INTO "elements" VALUES(182,'PointXY','Точка по координатам',11,17,NULL);
INSERT INTO "elements" VALUES(183,'Convertor','Конвертер величин',11,18,NULL);
INSERT INTO "elements" VALUES(184,'Informer','Информатор',11,19,NULL);
INSERT INTO "elements" VALUES(185,'ChangeMon','Мониторинг потока',11,20,NULL);
INSERT INTO "elements" VALUES(186,'VisualInline','Вставка кода',12,1,NULL);
INSERT INTO "elements" VALUES(187,'InlineCode','Вставка кода',12,2,NULL);
INSERT INTO "elements" VALUES(188,'Sleep','Задержка программы',12,3,NULL);
INSERT INTO "elements" VALUES(189,'Eval','Выполнение строки кода',12,4,NULL);
INSERT INTO "elements" VALUES(190,'Header','',12,5,NULL);
INSERT INTO "elements" VALUES(191,'NoErr','Отключение ошибок',12,6,NULL);
INSERT INTO "elements" VALUES(192,'ErrHandler','',12,7,NULL);
INSERT INTO "elements" VALUES(193,'ExecGlobal','Выполнение кода',12,8,NULL);
INSERT INTO "elements" VALUES(194,'Function','Создание функции',12,9,NULL);
INSERT INTO "elements" VALUES(195,'CallFunc','Вызов функции',12,10,NULL);
INSERT INTO "elements" VALUES(196,'WScript','Объект WScript',12,11,NULL);
INSERT INTO "elements" VALUES(197,'FieldRead','Чтение поля объекта',12,12,NULL);
INSERT INTO "elements" VALUES(198,'FieldWrite','Запись поля объекта',12,13,NULL);
INSERT INTO "elements" VALUES(199,'StrCat','Объединение строк',13,1,NULL);
INSERT INTO "elements" VALUES(200,'Length','Длина строки',13,2,NULL);
INSERT INTO "elements" VALUES(201,'Position','Позиция в строке',13,3,NULL);
INSERT INTO "elements" VALUES(202,'Copy','Часть строки',13,4,NULL);
INSERT INTO "elements" VALUES(203,'FormatStr','Форматированная строка',13,5,NULL);
INSERT INTO "elements" VALUES(204,'Replace','Замена',13,6,NULL);
INSERT INTO "elements" VALUES(205,'ArraySplit','Разбивка строки',13,7,NULL);
INSERT INTO "elements" VALUES(206,'StrList','Список строк',13,8,NULL);
INSERT INTO "elements" VALUES(207,'Trim','Удаление пробелов',13,9,NULL);
INSERT INTO "elements" VALUES(208,'StrCase','Регистр',13,10,NULL);
INSERT INTO "elements" VALUES(209,'Symbol','Спецсимволы',13,11,NULL);
INSERT INTO "elements" VALUES(210,'MultiStrData','Разбиение строки',13,12,NULL);
INSERT INTO "elements" VALUES(211,'RegExp','Регулярные выражения',13,13,NULL);
INSERT INTO "elements" VALUES(212,'Hashsum','Хэш сумма MD5',13,14,NULL);
INSERT INTO "elements" VALUES(213,'HexDump','Шестнадцатиричный дамп',13,15,NULL);
INSERT INTO "elements" VALUES(214,'TextConvertor','Перекодировка данных',13,16,NULL);
INSERT INTO "elements" VALUES(215,'Const','Определение константы',14,1,NULL);
INSERT INTO "elements" VALUES(216,'Color','Цветовая константа',14,2,NULL);
INSERT INTO "elements" VALUES(217,'WeekDay','Константа дня недели',14,3,NULL);
INSERT INTO "elements" VALUES(218,'Tristate','Булевая константа',14,4,NULL);
INSERT INTO "elements" VALUES(219,'*Helpers_Схема','Схема',15,1,NULL);
INSERT INTO "elements" VALUES(220,'Debug','Отладка',15,2,NULL);
INSERT INTO "elements" VALUES(221,'LineBreak','Разрыв связи',15,3,NULL);
INSERT INTO "elements" VALUES(222,'LineBreakEx','Разрыв линии',15,4,NULL);
INSERT INTO "elements" VALUES(223,'HubEx','Узел',15,5,NULL);
INSERT INTO "elements" VALUES(224,'GetDataEx','Узел',15,6,NULL);
INSERT INTO "elements" VALUES(225,'Check','Флажок',15,7,NULL);
INSERT INTO "elements" VALUES(226,'*Helpers_Дизайн','Дизайн',15,8,NULL);
INSERT INTO "elements" VALUES(227,'InfoTip','Вывеска',15,9,NULL);
INSERT INTO "elements" VALUES(228,'LinkTip','Ссылка',15,10,NULL);
INSERT INTO "elements" VALUES(229,'Shape','Фигура',15,11,NULL);
INSERT INTO "elements" VALUES(230,'PictureTip','Картинка в редакторе',15,12,NULL);
INSERT INTO "elements" VALUES(231,'PointHint','Сноска',15,13,NULL);
INSERT INTO "elements" VALUES(232,'ImageMulti','Схема в редакторе',15,14,NULL);
INSERT INTO "elements" VALUES(233,'ViewSHA','Схема в редакторе',15,15,NULL);
INSERT INTO "elements" VALUES(234,'*Helpers_Среда','Среда',15,16,NULL);
INSERT INTO "elements" VALUES(235,'SDKBtn','Кнопка на рабочем столе',15,17,NULL);
INSERT INTO "elements" VALUES(236,'AccessFTP','Доступ к FTP',15,18,NULL);
INSERT INTO "elements" VALUES(237,'ScriptEvents','События скрипта',15,19,NULL);
INSERT INTO "elements" VALUES(238,'BugReport','Сбор данных о схеме',15,20,NULL);
INSERT INTO "elements" VALUES(239,'MainForm','Форма',16,1,NULL);
INSERT INTO "elements" VALUES(240,'EntryPoint','Точка входа',16,2,NULL);
INSERT INTO "elements" VALUES(241,'WinControl','Элемент интерфейса',16,3,NULL);
INSERT INTO "elements" VALUES(242,'Form','Форма',16,4,NULL);
INSERT INTO "elements" VALUES(243,'Panel','Панель',16,5,NULL);
INSERT INTO "elements" VALUES(244,'GroupBox','Группа элементов',16,6,NULL);
INSERT INTO "elements" VALUES(245,'EditMultiEx','Редактор контейнера Ex',16,7,NULL);
INSERT INTO "elements" VALUES(246,'EditMulti','Редактор контейнера',16,8,NULL);
INSERT INTO "elements" VALUES(247,'PointElement','Точка',16,9,NULL);
INSERT INTO "elements" VALUES(248,'ReBar','Контейнер',16,10,NULL);
INSERT INTO "elements" VALUES(249,'Pager','Контейнер',16,11,NULL);
INSERT INTO "elements" VALUES(250,'TabControl','Закладки',16,12,NULL);
INSERT INTO "elements" VALUES(251,'Tab','Закладка',16,13,NULL);
INSERT INTO "elements" VALUES(252,'Img_Rectangle','Прямоугольник',16,14,NULL);
INSERT INTO "elements" VALUES(253,'Img_Line','Линия',16,15,NULL);
INSERT INTO "elements" VALUES(254,'Img_Ellipse','Эллипс',16,16,NULL);
INSERT INTO "elements" VALUES(255,'Img_Polygon','Многоугольник',16,17,NULL);
INSERT INTO "elements" VALUES(256,'Img_Text','Рисование текста',16,18,NULL);
INSERT INTO "elements" VALUES(257,'ChildForm','Дочерняя диалоговая форма',16,19,NULL);
INSERT INTO "elements" VALUES(258,'DialogForm','Дочерняя диалоговая форма',16,20,NULL);
INSERT INTO "elements" VALUES(259,'Message','Message Box',16,21,NULL);
INSERT INTO "elements" VALUES(260,'CustomCode','Пользовательский элемент',17,1,NULL);
INSERT INTO "elements" VALUES(261,'CG_LevelControl','Контроль уровня',17,2,NULL);
INSERT INTO "elements" VALUES(262,'CG_Trace','Отладка',17,3,NULL);
INSERT INTO "elements" VALUES(263,'CG_HiAsmVersion','Версия HiAsm',17,4,NULL);
INSERT INTO "elements" VALUES(264,'CG_BuildTime','Время сборки',17,5,NULL);
INSERT INTO "elements" VALUES(265,'CG_IDController','Управление ID',17,6,NULL);
INSERT INTO "elements" VALUES(266,'*CodeGen_Блоки','Блоки',17,7,NULL);
INSERT INTO "elements" VALUES(267,'CG_BlockPrint','Вывод блока',17,8,NULL);
INSERT INTO "elements" VALUES(268,'CG_BlockReg','Регистрация блока',17,9,NULL);
INSERT INTO "elements" VALUES(269,'CG_BlockSelect','Выбор блока',17,10,NULL);
INSERT INTO "elements" VALUES(270,'CG_BlockDelete','Удаление блока',17,11,NULL);
INSERT INTO "elements" VALUES(271,'CG_BlockIncLevel','Увеличение отступа',17,12,NULL);
INSERT INTO "elements" VALUES(272,'CG_BlockDecLevel','Уменьшение отступа',17,13,NULL);
INSERT INTO "elements" VALUES(273,'Beep','Бип из динамика',18,1,NULL);
INSERT INTO "elements" VALUES(274,'RegistryWMI','Системный реестр',19,1,NULL);
INSERT INTO "elements" VALUES(275,'RegistryEventsWMI','События реестра',19,2,NULL);
INSERT INTO "elements" VALUES(276,'ProcessCheckWMI','Статус процесса',19,3,NULL);
INSERT INTO "elements" VALUES(277,'ProcessEventsWMI','События процесса',19,4,NULL);
INSERT INTO "elements" VALUES(278,'ProcessEnumWMI','Перебор процессов',19,5,NULL);
INSERT INTO "elements" VALUES(279,'ProcessControlWMI','Управление процессом',19,6,NULL);
INSERT INTO "elements" VALUES(280,'ScheduledJobWMI','Создание задания',19,7,NULL);
INSERT INTO "elements" VALUES(281,'PingStatusWMI','Ping компьютера',19,8,NULL);
INSERT INTO "elements" VALUES(282,'CPUusageWMI','Нагрузка на ЦПУ',19,9,NULL);
INSERT INTO "elements" VALUES(283,'ConnectWMI','Соединение с WMI',19,10,NULL);
INSERT INTO "elements" VALUES(284,'ExitWindowsWMI','Выход из системы',19,11,NULL);
INSERT INTO "elements" VALUES(285,'MT_Add','Добавление элемента',20,1,NULL);
INSERT INTO "elements" VALUES(286,'MT_Get','Чтение данных из многомерного потока',20,2,NULL);
INSERT INTO "elements" VALUES(287,'MT_IndexToChannel','Вызывает событие по индексу в потоке',20,3,NULL);
INSERT INTO "elements" VALUES(288,'MT_ChannelToIndex','Возвращает индекс активированной точки входа',20,4,NULL);
INSERT INTO "elements" VALUES(289,'MT_MTtoDataChannel','Перевод МТ потока в последовательные каналы данных',20,5,NULL);
INSERT INTO "elements" VALUES(290,'MT_Enum','Перебор данных многомерного потока',20,6,NULL);
INSERT INTO "elements" VALUES(291,'Printf','Строка по шаблону',13,17,NULL);
INSERT INTO "elements" VALUES(292,'Inline','Вставка нативного фрагмента',12,14,NULL);
CREATE TABLE files(id INTEGER PRIMARY KEY AUTOINCREMENT,name varchar(128),count int);
CREATE TABLE files_link(file_id int,el_id int);
COMMIT;
