BEGIN TRANSACTION;
CREATE TABLE groups(id INTEGER PRIMARY KEY AUTOINCREMENT, name varchar(64), info varchar(128), pos int);
INSERT INTO "groups" VALUES(1,'','',1);
INSERT INTO "groups" VALUES(2,'Helpers','Помощники',10);
INSERT INTO "groups" VALUES(3,'HiAsm','HiAsm',3);
INSERT INTO "groups" VALUES(4,'Main','Main',2);
INSERT INTO "groups" VALUES(5,'Arrays','Массивы',7);
INSERT INTO "groups" VALUES(6,'Make','Make',5);
INSERT INTO "groups" VALUES(7,'Service','Service',11);
INSERT INTO "groups" VALUES(8,'Strings','Строки',8);
INSERT INTO "groups" VALUES(9,'ServiceOS','Сервис ОС',9);
INSERT INTO "groups" VALUES(11,'Forms','Формы',6);
INSERT INTO "groups" VALUES(36,'Core','Core',4);
DELETE FROM sqlite_sequence;
INSERT INTO "sqlite_sequence" VALUES('groups',37);
INSERT INTO "sqlite_sequence" VALUES('elements',566);
CREATE TABLE elements(id INTEGER PRIMARY KEY AUTOINCREMENT, name varchar(64), info varchar(64), tab int, pos int, hash varchar(32));
INSERT INTO "elements" VALUES(1,'*Helpers_Схема','Схема',2,1,NULL);
INSERT INTO "elements" VALUES(2,'LineBreak','Разрыв линии',2,2,NULL);
INSERT INTO "elements" VALUES(3,'GetDataEx','Продвинутый Доступ к данным',2,4,NULL);
INSERT INTO "elements" VALUES(4,'Check','Флажок',2,5,NULL);
INSERT INTO "elements" VALUES(5,'*Helpers_Дизайн','Дизайн',2,6,NULL);
INSERT INTO "elements" VALUES(6,'InfoTip','Вывод подсказки в окне редактора',2,7,NULL);
INSERT INTO "elements" VALUES(7,'LinkTip','Гиперссылка в редакторе',2,8,NULL);
INSERT INTO "elements" VALUES(8,'Shape','Фигура',2,9,NULL);
INSERT INTO "elements" VALUES(9,'PictureTip','Отображение картинки в редакторе программы',2,10,NULL);
INSERT INTO "elements" VALUES(10,'PointHint','Сноска',2,11,NULL);
INSERT INTO "elements" VALUES(11,'ImageMulti','Отображение схем в редакторе',2,12,NULL);
INSERT INTO "elements" VALUES(12,'ViewSHA','Отображение схем в редакторе',2,13,NULL);
INSERT INTO "elements" VALUES(13,'*Helpers_Среда','Среда',2,14,NULL);
INSERT INTO "elements" VALUES(14,'SDKBtn','Кнопка на рабочем столе',2,15,NULL);
INSERT INTO "elements" VALUES(15,'AccessFTP','Доступ к FTP',2,16,NULL);
INSERT INTO "elements" VALUES(16,'ScriptEvents','События скрипта',2,17,NULL);
INSERT INTO "elements" VALUES(17,'HISEntryPoint','Точка входа HIS',1,1,NULL);
INSERT INTO "elements" VALUES(18,'AddElement','Регистрация элемента',3,1,NULL);
INSERT INTO "elements" VALUES(19,'Message','Сообщение',7,1,NULL);
INSERT INTO "elements" VALUES(20,'CheckElement','Проверка элемента',3,2,NULL);
INSERT INTO "elements" VALUES(21,'If_else','Условие',4,2,NULL);
INSERT INTO "elements" VALUES(22,'*Main_Логика','Логика',4,1,NULL);
INSERT INTO "elements" VALUES(23,'Case','Выбор значения',4,3,NULL);
INSERT INTO "elements" VALUES(24,'For','Цикл',4,4,NULL);
INSERT INTO "elements" VALUES(25,'*Main_Инструменты','Инструменты',4,6,NULL);
INSERT INTO "elements" VALUES(26,'Hub','Хаб',4,7,NULL);
INSERT INTO "elements" VALUES(27,'DoData','Поток-данные',4,8,NULL);
INSERT INTO "elements" VALUES(28,'Memory','Память',4,9,NULL);
INSERT INTO "elements" VALUES(29,'VisualText','Вставка текста',4,10,NULL);
INSERT INTO "elements" VALUES(30,'Environment','Окружение',3,10,NULL);
INSERT INTO "elements" VALUES(31,'AddCompiler','Регистрация компилятора',3,4,NULL);
INSERT INTO "elements" VALUES(32,'SetCompiler','Назначение компилятора',3,5,NULL);
INSERT INTO "elements" VALUES(33,'AddPack','Регистрация пакета',3,6,NULL);
INSERT INTO "elements" VALUES(34,'AddProject','Регистрация проекта',3,9,NULL);
INSERT INTO "elements" VALUES(35,'StrArray','Массив строк',5,1,NULL);
INSERT INTO "elements" VALUES(36,'ArrayRead','Чтение массива',5,2,NULL);
INSERT INTO "elements" VALUES(37,'ArraySize','Размер массива',5,3,NULL);
INSERT INTO "elements" VALUES(38,'ArrayEnum','Перебор массива',5,4,NULL);
INSERT INTO "elements" VALUES(39,'ArrayWrite','Запись в массив',5,5,NULL);
INSERT INTO "elements" VALUES(40,'DelPack','Удаление пакета',3,7,NULL);
INSERT INTO "elements" VALUES(41,'MakeEntryPoint','Точка входа make',1,2,NULL);
INSERT INTO "elements" VALUES(42,'GetParams','Получение параметров',6,1,NULL);
INSERT INTO "elements" VALUES(43,'MakeProject','Сборка проекта',6,2,NULL);
INSERT INTO "elements" VALUES(44,'Complite','Завершение сборки',6,3,NULL);
INSERT INTO "elements" VALUES(45,'RunProject','Запуск приложения',6,4,NULL);
INSERT INTO "elements" VALUES(46,'StopProject','Останов приложения',6,5,NULL);
INSERT INTO "elements" VALUES(47,'StrCat','Объединение строк',8,1,NULL);
INSERT INTO "elements" VALUES(48,'Length','Длинна строки',8,2,NULL);
INSERT INTO "elements" VALUES(49,'*ServiceOS_Файлы','Файлы',9,1,NULL);
INSERT INTO "elements" VALUES(50,'DirOperation','Операции с папками',9,2,NULL);
INSERT INTO "elements" VALUES(51,'CreateProcess','Запуск процесса',9,5,NULL);
INSERT INTO "elements" VALUES(52,'*ServiceOS_Процессы','Процессы',9,4,NULL);
INSERT INTO "elements" VALUES(53,'WaitObject','Синхронизация',9,7,NULL);
INSERT INTO "elements" VALUES(54,'While','Цикл с условием',4,5,NULL);
INSERT INTO "elements" VALUES(55,'FileOperation','Операции с файлами',9,3,NULL);
INSERT INTO "elements" VALUES(56,'Replace','Замена',8,3,NULL);
INSERT INTO "elements" VALUES(57,'TerminateProcess','Завершение процесса',9,6,NULL);
INSERT INTO "elements" VALUES(59,'MainForm','Форма',11,1,NULL);
INSERT INTO "elements" VALUES(60,'WinControl','Элемент интерфейса',1,3,NULL);
INSERT INTO "elements" VALUES(61,'Label','Нaдпиcь',11,2,NULL);
INSERT INTO "elements" VALUES(62,'Button','Кнопка',11,3,NULL);
INSERT INTO "elements" VALUES(63,'Edit','Поле ввода',11,4,NULL);
INSERT INTO "elements" VALUES(64,'ComboBox','Выпадающий список',11,5,NULL);
INSERT INTO "elements" VALUES(65,'ListBox','Cпиcoк cтpoк',11,6,NULL);
INSERT INTO "elements" VALUES(66,'Memo','Peдaктop тeкcтa',11,7,NULL);
INSERT INTO "elements" VALUES(67,'Panel','Панель',1,4,NULL);
INSERT INTO "elements" VALUES(68,'ChildPanel','Панель',11,8,NULL);
INSERT INTO "elements" VALUES(69,'EditMulti','Редактор компонента MultiElement',1,5,NULL);
INSERT INTO "elements" VALUES(70,'Image','Изображение',11,9,NULL);
INSERT INTO "elements" VALUES(71,'RadioButton','Пepeключaтeль',11,10,NULL);
INSERT INTO "elements" VALUES(72,'BitBtn','Кнопка с картинкой',11,15,NULL);
INSERT INTO "elements" VALUES(73,'ChildGroupBox','Группа элементов',11,11,NULL);
INSERT INTO "elements" VALUES(74,'GroupBox','Группа элементов',1,6,NULL);
INSERT INTO "elements" VALUES(75,'TabControl','Контроллёр страниц',11,12,NULL);
INSERT INTO "elements" VALUES(76,'CheckBox','Флажок',11,13,NULL);
INSERT INTO "elements" VALUES(77,'StringTable','Таблица строк',11,14,NULL);
INSERT INTO "elements" VALUES(78,'AddGroup','Создание группы',3,3,NULL);
INSERT INTO "elements" VALUES(482,'hcButton','Кнопка',36,2,NULL);
INSERT INTO "elements" VALUES(483,'hcHub','Разветвитель',36,23,NULL);
INSERT INTO "elements" VALUES(484,'hcDoData','Поток-данные',36,24,NULL);
INSERT INTO "elements" VALUES(485,'*Core_Инструменты','Инструменты',36,22,NULL);
INSERT INTO "elements" VALUES(486,'hcIf_else','Условный блок',36,25,NULL);
INSERT INTO "elements" VALUES(487,'hcTimer','Таймер',36,30,NULL);
INSERT INTO "elements" VALUES(488,'hcMath','Арифметические операции +,-,*,/,... (и т.п. по списку в OpType)',36,27,NULL);
INSERT INTO "elements" VALUES(489,'hcTrace','Трассировка',36,54,NULL);
INSERT INTO "elements" VALUES(490,'*Core_Среда','Среда',36,53,NULL);
INSERT INTO "elements" VALUES(491,'hcVisualText','Вставка текста',36,3,NULL);
INSERT INTO "elements" VALUES(492,'hcFor','Цикл со счетчиком',36,26,NULL);
INSERT INTO "elements" VALUES(493,'hcCommander','Вызов команд',36,55,NULL);
INSERT INTO "elements" VALUES(494,'hcCommanHandler','Обработчик команд',36,58,NULL);
INSERT INTO "elements" VALUES(495,'hcRandom','Случайное число',36,31,NULL);
INSERT INTO "elements" VALUES(496,'hcMessage','Сообщение',36,32,NULL);
INSERT INTO "elements" VALUES(497,'hcBeep','Сигнал',36,33,NULL);
INSERT INTO "elements" VALUES(498,'hcListBox','Список строк',36,4,NULL);
INSERT INTO "elements" VALUES(499,'*Files_Безопасность','Безопасность',12,22,NULL);
INSERT INTO "elements" VALUES(500,'FileSecurity','Безопасность файла',12,23,NULL);
INSERT INTO "elements" VALUES(501,'ChangeFileSecurity','Безопасность файла',12,24,NULL);
INSERT INTO "elements" VALUES(502,'FSOwner','Владелец файла',12,25,NULL);
INSERT INTO "elements" VALUES(503,'SIDConvertor','Конвертор SID',12,26,NULL);
INSERT INTO "elements" VALUES(504,'SIDInfo','Информация о SID',12,27,NULL);
INSERT INTO "elements" VALUES(505,'hcAddElement','Вставка элемента',36,50,NULL);
INSERT INTO "elements" VALUES(506,'*Core_Элементы','Элементы',36,49,NULL);
INSERT INTO "elements" VALUES(507,'hcStrCat','Соединение двух строк в одну',36,37,NULL);
INSERT INTO "elements" VALUES(508,'hcConnectElement','Соединение точек элементов',36,52,NULL);
INSERT INTO "elements" VALUES(509,'hcMoveElement','Перемещение элемента',36,51,NULL);
INSERT INTO "elements" VALUES(511,'hcSDKEvents','События схемы',36,59,NULL);
INSERT INTO "elements" VALUES(512,'hcKeyHandler','Обработчик клавиатуры',36,60,NULL);
INSERT INTO "elements" VALUES(513,'hcMouseHandler','Обработчик мыши',36,61,NULL);
INSERT INTO "elements" VALUES(514,'*Core_Шаблоны','Шаблоны',36,5,NULL);
INSERT INTO "elements" VALUES(515,'hcTplForm','Шаблон формы',36,19,NULL);
INSERT INTO "elements" VALUES(516,'hcRunSHA','Запуск SHA',36,56,NULL);
INSERT INTO "elements" VALUES(517,'hcTplButton','Кнопка',36,6,NULL);
INSERT INTO "elements" VALUES(518,'hcTplLabel','Нaдпиcь',36,7,NULL);
INSERT INTO "elements" VALUES(519,'hcMemory','Память',36,34,NULL);
INSERT INTO "elements" VALUES(520,'hcStrList','Список строк',36,39,NULL);
INSERT INTO "elements" VALUES(521,'hcHTTPText','Загрузка текста',36,46,NULL);
INSERT INTO "elements" VALUES(522,'*Core_Network','Network',36,45,NULL);
INSERT INTO "elements" VALUES(523,'hcArrayEnum','Перебор массива',36,44,NULL);
INSERT INTO "elements" VALUES(524,'*Core_Массивы','Массивы',36,42,NULL);
INSERT INTO "elements" VALUES(525,'hcFormatStr','Форматированная строка',36,40,NULL);
INSERT INTO "elements" VALUES(526,'*Core_Строки','Строки',36,36,NULL);
INSERT INTO "elements" VALUES(527,'hcTplListBox','Список строк',36,10,NULL);
INSERT INTO "elements" VALUES(528,'hcHiAsmTrasmitter','Коммуникация со средой',36,57,NULL);
INSERT INTO "elements" VALUES(529,'hcMT_Get','Получение данных',36,48,NULL);
INSERT INTO "elements" VALUES(530,'*Core_MT потоки','MT потоки',36,47,NULL);
INSERT INTO "elements" VALUES(531,'hcClipboard','Буфер обмена',36,35,NULL);
INSERT INTO "elements" VALUES(532,'hcTplEdit','Поле ввода',36,8,NULL);
INSERT INTO "elements" VALUES(533,'hcTplMemo','Поле ввода',36,9,NULL);
INSERT INTO "elements" VALUES(534,'hcTplSynEdit','Поле ввода',36,14,NULL);
INSERT INTO "elements" VALUES(536,'hcTplTabControl','Контроллёр страниц',36,15,NULL);
INSERT INTO "elements" VALUES(537,'hcPopupMenu','Контекстное меню',36,16,NULL);
INSERT INTO "elements" VALUES(538,'*Core_Интерфейс SDK','Интерфейс SDK',36,1,NULL);
INSERT INTO "elements" VALUES(539,'MultiElement','Вложенная схема',36,28,NULL);
INSERT INTO "elements" VALUES(540,'hcChildForm','Дочерняя форма',36,18,NULL);
INSERT INTO "elements" VALUES(541,'EditMultiEx','Редактор компонента MultiElement',1,7,NULL);
INSERT INTO "elements" VALUES(542,'hcTplScrollBar','Панель прокрутки',36,12,NULL);
INSERT INTO "elements" VALUES(543,'hcConvertor','Конвертер одной величины в другую',36,29,NULL);
INSERT INTO "elements" VALUES(544,'hcStrPos','Возвращает позицию вхождения одной строки в другую',36,38,NULL);
INSERT INTO "elements" VALUES(545,'hcTplBitBtn','Кнопка',36,13,NULL);
INSERT INTO "elements" VALUES(546,'hcTplPanel','Панель',1,8,NULL);
INSERT INTO "elements" VALUES(547,'hcChildPanel','Панель',36,17,NULL);
INSERT INTO "elements" VALUES(548,'hcTplComboBox','Выпадающий список',36,11,NULL);
INSERT INTO "elements" VALUES(549,'hcTplSDKEdit','Редактор SHA',36,20,NULL);
INSERT INTO "elements" VALUES(550,'hcSdeHint','Подсказка в редакторе',36,62,NULL);
INSERT INTO "elements" VALUES(551,'hcElements','Элементы пакета',36,63,NULL);
INSERT INTO "elements" VALUES(552,'hcElementTpl','Шаблон элемента',36,64,NULL);
INSERT INTO "elements" VALUES(553,'hcETplEnumProps','Перечисление св-тв шаблона',36,65,NULL);
INSERT INTO "elements" VALUES(554,'hcETplEnumMethods','Перечисление точек шаблона элемента',36,66,NULL);
INSERT INTO "elements" VALUES(555,'hcArrayRead','Чтение массива',36,43,NULL);
INSERT INTO "elements" VALUES(556,'hcSaveDialog','Сохранение файла',36,67,NULL);
INSERT INTO "elements" VALUES(557,'hcOpenDialog','Открытие файла',36,68,NULL);
INSERT INTO "elements" VALUES(558,'ShellExecuteEx','Запуск файла зарегистрированным для него приложением',9,6,NULL);
INSERT INTO "elements" VALUES(559,'hcTplColorPicker','Выбор цвета',36,21,NULL);
INSERT INTO "elements" VALUES(560,'hcDS_SQLite','Источник данных SQLite',36,70,NULL);
INSERT INTO "elements" VALUES(561,'hcDSC_Exec','Запрос на выполнение',36,71,NULL);
INSERT INTO "elements" VALUES(562,'hcDSC_Query','Запрос данных',36,72,NULL);
INSERT INTO "elements" VALUES(563,'hcDSC_QueryScalar','Запрос одной ячейки',36,73,NULL);
INSERT INTO "elements" VALUES(564,'*Core_DataBase','DataBase',36,69,NULL);
INSERT INTO "elements" VALUES(565,'hcCopy','Копирует часть строки',36,41,NULL);
INSERT INTO "elements" VALUES(566,'hcTplCheckBox','Флажок',36,74,NULL);
CREATE TABLE files(id INTEGER PRIMARY KEY AUTOINCREMENT, name varchar(128), count int);
CREATE TABLE files_link(file_id int, el_id int);
COMMIT;
